name: FrequentFlyer-v1.4-Premium
main: BaliGamerz899\Main
api: [3.0.0, 3.0.1, 4.0.0]
version: 1.0
author: BaliGamerz   //No Edit Author

commands:
  ff:
    description: §o§bMemberikan sayap
    permission: ff.item
    usage: /ff
    
permissions:
  ff.item:
    default: op
    description: §o§bMemberikan sayap
